### ISSUE TITLE
Lilien haben einen schlechten Kontrast zur Karte

### ISSUE THREAD

**Issue by MrEbbinghaus** [deutscher-pfadfinderbund/karte#6]
Ich finde, dass die Lilien alleine recht schlecht auf der Karte zu sehen sind. 
Bei den Wappen fällt das nicht so auf, weil die "solider" sind. Heißt kräftige, meist flächige Farben, die sich vom Hintergrund abheben. 

![image](https://github.com/deutscher-pfadfinderbund/karte/assets/2965273/32dfa2e2-874c-4d12-8f25-dc6c9c9e19f1)

## Marker Container

Vielleicht sollten wir für Wappen / Logos generell einen Container festlegen um Kontrast und Größe stabil zu halten. Alle Marker sollten gleich groß auf der Karte erscheinen, was nicht klappt, wenn manche Logos einen transparenten Rand haben. 

Hier sieht man auch: Der Kontrast vom Schloss Martinfeld Logo ist nicht gut und die Symbole für Heime sind sehr viel mächtiger. 
![image](https://github.com/deutscher-pfadfinderbund/karte/assets/2965273/e1760f6e-d1a7-44e9-9350-4225431163cc)

### Mögliche Marker Container
Vielleicht sollten alle Logos in Markern sein? 

![image](https://github.com/deutscher-pfadfinderbund/karte/assets/2965273/caa89328-be9e-4e30-b947-35cc02c71e1a)

**Comment by btreb** [comment]
Das mit der Sichtbarkeit und der Größe von Lilien, Wappen/Logos und Symbolen ist mir so auch schon aufgefallen. Die Idee alles in Marker zu verpacken finde ich eine super Lösung. Ich hatte da schon eine ganz ähnliche Idee. Vllt kommt ich die Tage mal dazu die lokal umzusetzen und hier Bilder hinzuzufügen

**Comment by btreb** [comment]
Das wäre eine recht simple Variante über "divIcon" mit verschiedenen Markerfarben für Gruppen und Heime. Bei den Gruppen geht das gut, da die Abmessungen von Lilie und Wappen immer ähnlich sind, bei den Heimen macht das z.B. bei Martinfeld Probleme, so dass ich hier wohl nur noch das Symbol verwenden würde. Die Größe der Marker ist dabei immer 40x40px. Und dadurch, dass die Marker Divs sind könnte #7 recht simpel über das title-Attribut gelöst werden.

![Wappen und Lilie im Marker](https://github.com/deutscher-pfadfinderbund/karte/assets/48634632/f49444d9-72de-469f-a231-738cd27e0eaa)

![Bei Heimen Haussymbol](https://github.com/deutscher-pfadfinderbund/karte/assets/48634632/60b291ef-aeed-4176-8cfd-ca6e25611c8d)
